name: bakumote
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1

  cupertino_icons: ^0.1.3

  # Widget
  bubble:
  photo_view:
  image_picker:
  image_cropper:
  pull_to_refresh:
  auto_size_text:
  adaptive_dialog:
  flutter_picker:
  badges:

  # Database
  shared_preferences:
  objectbox:
  objectbox_flutter_libs:

  # RemiSpecial
  flutter_hooks:
  hooks_riverpod:
  freezed_annotation:

  # Other
  package_info:
  rxdart:
  path_provider:
  simple_logger:
  date_calc:
  uuid:
  hashids2:
  flutter_local_notifications:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono:
  build_runner:
  intl_translation:
  freezed:
  objectbox_generator:
  json_serializable:
  flutter_launcher_icons:

dependency_overrides:
  analyzer: '>=0.39.5 <0.40.0'

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
  adaptive_icon_background: "#FFF"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/icon/

